// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgusiunwlrrkxnktqnnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndndXNpdW53bHJya3hua3Rxbm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMTY3NjMsImV4cCI6MjA1Mzc5Mjc2M30.HKlAf_5mWu9DGB9glzRLO2N_NDVemhKLJEMSoNrOAjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);